Multi-catch block in One Try :-
=============================


 

public class test 
 {
   public static void main (String []args)
   {
     int a = 10 ;
     int b = 0 ;
     int c ;
     try {
       c=a/b;
     System.out.println(c);
     } 
     catch(ArithmeticException e)
     {
       System.out.println(e);
     }
     catch(ArrayIndexOutOfBoundsException e)
     {
       System.out.println(e);
     }
     catch(Exception e) 
     {
       System.out.println(e);
     }
     
     
     c=a+b;
     System.out.println(c);
     c=a-b;
     System.out.println(c);
     c=a*b;
     System.out.println(c);
     
   }
 }